/**
 * Test Fixtures for Monolith ERP Testing Suites
 * Contains standardized persona profiles, requests, department configurations,
 * and test data models across Tiers 1-5.
 */

export const FIXTURES = {
  // 5-Tier Representative Personas
  personas: {
    tier1_intern: {
      id: "USR-008",
      email: "employee@company.com",
      password: "password123",
      tier: 1,
      role: "employee",
      name: "Udeh Kosisochukwu Emmanuel",
      title: "Software Developer Intern",
      department: "Engineering",
      managerId: "USR-005",
      salary: "$3,500/mo",
      monthlyBasePay: 3500,
      annualLeaveBalance: 14,
      sickLeaveBalance: 8,
      casualLeaveBalance: 4,
    },
    tier2_senior: {
      id: "USR-009",
      email: "chidi.ui@company.com",
      password: "password123",
      tier: 2,
      role: "employee",
      name: "Chidi Nnamdi",
      title: "Product Designer & UI Engineer",
      department: "Product & Design",
      managerId: "USR-005",
      salary: "$4,200/mo",
      monthlyBasePay: 4200,
      annualLeaveBalance: 16,
      sickLeaveBalance: 9,
      casualLeaveBalance: 5,
    },
    tier3_lead: {
      id: "USR-005",
      email: "sarah.chen@company.com",
      password: "password123",
      tier: 3,
      role: "manager",
      name: "Sarah Chen",
      title: "Frontend & Mobile Engineering Lead",
      department: "Engineering",
      managerId: "USR-002",
      salary: "$6,200/mo",
      monthlyBasePay: 6200,
      annualLeaveBalance: 18,
      sickLeaveBalance: 10,
      casualLeaveBalance: 5,
    },
    tier4_director_eng: {
      id: "USR-002",
      email: "vpeng@company.com",
      password: "password123",
      tier: 4,
      role: "director",
      name: "Tunde Bakare",
      title: "VP of Technology & Engineering",
      department: "Engineering",
      managerId: "USR-001",
      salary: "$9,800/mo",
      monthlyBasePay: 9800,
      annualLeaveBalance: 24,
      sickLeaveBalance: 12,
      casualLeaveBalance: 5,
    },
    tier4_director_finance: {
      id: "USR-004",
      email: "finance@company.com",
      password: "password123",
      tier: 4,
      role: "finance",
      name: "Marcus Brody",
      title: "Head of Finance & Corporate Operations",
      department: "Finance & Operations",
      managerId: "USR-001",
      salary: "$8,200/mo",
      monthlyBasePay: 8200,
      annualLeaveBalance: 22,
      sickLeaveBalance: 10,
      casualLeaveBalance: 5,
    },
    tier4_director_hr: {
      id: "USR-003",
      email: "admin@company.com",
      password: "password123",
      tier: 4,
      role: "admin",
      name: "Victoria Sterling",
      title: "VP of People Operations & Culture",
      department: "Human Resources",
      managerId: "USR-001",
      salary: "$8,500/mo",
      monthlyBasePay: 8500,
      annualLeaveBalance: 25,
      sickLeaveBalance: 12,
      casualLeaveBalance: 5,
    },
    tier5_ceo: {
      id: "USR-001",
      email: "ceo@company.com",
      password: "password123",
      tier: 5,
      role: "executive",
      name: "Dr. Alexander Vance",
      title: "Chief Executive Officer & Co-Founder",
      department: "Executive",
      managerId: null,
      salary: "$18,500/mo",
      monthlyBasePay: 18500,
      annualLeaveBalance: 30,
      sickLeaveBalance: 15,
      casualLeaveBalance: 7,
    },
  },

  // Sample Leave Applications
  leaves: {
    validAnnual: {
      type: "Annual Leave",
      dates: "2026-09-10 - 2026-09-14",
      days: 4,
      reason: "Family vacation and travel",
    },
    validSick: {
      type: "Sick Leave",
      dates: "2026-09-02 - 2026-09-03",
      days: 2,
      reason: "Doctor appointment and recovery",
    },
    validCasual: {
      type: "Casual Leave",
      dates: "2026-09-20 - 2026-09-20",
      days: 1,
      reason: "Personal administrative errands",
    },
  },

  // Sample Expense Claims
  claims: {
    internetAllowance: {
      category: "Internet & Remote Work",
      amount: "$120.00",
      description: "Monthly high-speed internet reimbursement",
      receipt: "internet_bill_aug.pdf",
    },
    softwareLicense: {
      category: "Software Asset",
      amount: "$85.00",
      description: "Code editor and productivity tools annual license",
      receipt: "license_receipt.pdf",
    },
    travelReimbursement: {
      category: "Travel & Logistics",
      amount: "$450.00",
      description: "Client on-site technical meeting transport and lodging",
      receipt: "flight_hotel_invoice.pdf",
    },
  },

  // Department metadata
  departments: [
    { id: "DEP-ENG", name: "Engineering & Technology", code: "ENG", budget: 42000 },
    { id: "DEP-HR", name: "Human Resources & Talent", code: "HR", budget: 18500 },
    { id: "DEP-FIN", name: "Finance & Corporate Operations", code: "FIN", budget: 24000 },
    { id: "DEP-PRD", name: "Product & Design", code: "PRD", budget: 16000 },
  ],
};
